spring:
  mvc:
    format:
      date: yyyy-MM-dd
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/testwork"
    username: testworkjava
    password: password