CREATE TABLE IF NOT EXISTS public.division
(
    division_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    division_name character varying(150) COLLATE pg_catalog."default",
    parent_id integer,
    dt_from date NOT NULL,
    dt_till date,
    is_system integer,
    creation_date timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    correction_date timestamp with time zone,
    CONSTRAINT pk_division_id PRIMARY KEY (division_id),
    CONSTRAINT fk_parent_id_refer_to_id FOREIGN KEY (parent_id)
        REFERENCES public.division (division_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.division
    OWNER to postgres;

REVOKE ALL ON TABLE public.division FROM testworkjava;

GRANT ALL ON TABLE public.division TO postgres;

GRANT SELECT, INSERT, TRIGGER, REFERENCES, UPDATE, DELETE ON TABLE public.division TO testworkjava;